name = "totp"
compatibility_date = "2024-09-25"

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "directory" 
dir = "./dist"

# Production deployment settings
[env.production]
name = "totp"

# Define production branch
[pages]
production_branch = "master"
